using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Data;
using TeamRedInternalProject.Models;
using TeamRedInternalProject.Repositories;
using TeamRedInternalProject.ViewModel;

namespace TeamRedInternalProject.Controllers
{
    [Authorize(Roles = "Admin")]
    public class AdminController : Controller
    {
        private readonly ILogger<AdminController> _logger;
        private readonly ConcertContext _db;
        private readonly AdminRepo _adminRepo;



        public AdminController(ILogger<AdminController> logger, ConcertContext db)
        {
            _logger = logger;
            _adminRepo = new AdminRepo(db);
            _db = db;
        }

        /// <summary>
        /// Load all data for admin dashboard:
        /// 1. Total Number of Tickets Purchased
        /// 2. Total Ticket Revenue
        /// 3. Ticket Revenue By Tickete Type (in table)
        /// All data is for current festival
        /// </summary>
        /// <returns>Admin dashboard view</returns>
        public IActionResult Index(string message="")
        {
            if(message != "")
            {
                ViewData["DeleteErrorMessage"] = message;
            }
            
            // Data by type for the table
            List<TicketSalesVM> ticketRevenueVMs = _adminRepo.GetTicketSalesDataByTicketType();

            // Summary stats (totals)
            int totalTicketsPurchased = _adminRepo.GetTotalTicketsSold();
            decimal totalRevenue = _adminRepo.GetTotalRevenue(ticketRevenueVMs);

            ViewData["TotalTicketsPurchased"] = totalTicketsPurchased;
            ViewData["TotalRevenue"] = totalRevenue;
            
            // later add a github like heat map for tickets sold or revenue generated by day of calendar?

            return View(ticketRevenueVMs);
        }

    }
}
